# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '47 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install scoop
      run: |
        iwr -useb get.scoop.sh | iex
        "::add-path::$home\scoop\shims"

    - name: hacks
      run: bin\hacks.ps1

    - name: auto-pr
      run: |
        $ErrorActionPreference = 'Continue'
        hub config --global user.name github-actions
        hub config --global user.email qx@qianxi.ml
        bin\auto-pr.ps1 -Push -SpecialSnowflakes $env:SpecialSnowflakes
